services:
  frontend:
    build: 
      context: ./frontend
      target: builder
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

  backend:
    build: ./backend-service
    volumes:
      - ./backend-service:/app
      - /app/node_modules
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=dev
      - DB_PASSWORD=dev
      - DB_NAME=dev_db
    depends_on:
      - postgres
      - migration-service
    command: npx @nestjs/cli start --watch

  auth:
    build:
      context: ./auth-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./auth-service:/app
      - /app/node_modules
    environment:
      - JWT_SECRET=dev_secret
      - DB_HOST=postgres
      - DB_PORT=5432
    depends_on:
      - postgres
      - migration-service
    command: npx @nestjs/cli start --watch

  swagger:
    build: 
      context: ./swagger-service
      target: builder
    volumes:
      - ./swagger-service:/app
    environment:
      - PORT=3002
    ports:
      - "3002:3002"
    command: npx @nestjs/cli start --watch

  postgres:
    image: postgres:15
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=dev_db

  migration-service:
    build: ./migration-service
    container_name: migration-service
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=dev
      - DB_PASSWORD=dev
      - DB_NAME=dev_db

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/dev.conf:/etc/nginx/nginx.conf
    depends_on:
      auth:
        condition: service_started
      backend:
        condition: service_started
      swagger:
        condition: service_started
      frontend:
        condition: service_started
      migration-service:
        condition: service_completed_successfully

volumes:
  postgres_dev_data: