apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: infra-kata
type: Opaque
data:
  # base64 encoded values
  # For example, echo -n 'your_password' | base64
  jwt-secret: ZGV2X3NlY3JldA== # base64 encoded 'dev_secret'
  db-password: ZGV2 # base64 encoded 'dev'
  db-name: ZGV2X2Ri # base64 encoded 'dev_db'
  db-user: ZGV2 # base64 encoded 'dev'